- .github/workflows/backend-ci.yml
* Github Actions을 활용한 CI 구축
* main 브랜치로 push, pull request시 자동으로 빌드하고 테스트 수행
> [#8] 자동 빌드 & 테스트 CI 구축 

- backend/Dockerfile
- backend/build.gradle
- backend/src/main/java/com/huemap/backend/common/presentation/HealthCheckController.java
- backend/src/main/resources/application.yml
- docker-compose.yml
- nginx/Dockerfile
- nginx/conf.d/app.conf
도커 설정파일 생성
nginx, mysql, spring 컨테이너 생성 성공
aws ec2 환경에서 테스트 완료
HealthCheck 전용 컨트롤러 생성
> [#12] 도커 설정파일 생성

- .github/workflows/backend-ci.yml
> [#29] fix: CI 이벤트 발생 브랜치 수정

- .github/workflows/backend-ci.yml
- .gitignore
- backend/src/main/java/com/huemap/backend/user/domain/User.java
- backend/src/main/resources/application.yml
- docker-compose.yml
> [#32] AWS RDS 적용

- backend/src/main/java/com/huemap/backend/BackendApplication.java
- backend/src/main/java/com/huemap/backend/common/entity/BaseEntity.java
- backend/src/main/java/com/huemap/backend/user/domain/User.java
* id, 생성시간, 수정시간을 담은 BaseEntity 생성
> [#41] Base Entity 생성

- .github/workflows/backend-ci.yml
* Pull Request를 올릴 때 동작하는 CI가 여러 번 동작하는 것을 수정하였습니다.
> [#49] ci 반복 수정

- backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
- backend/src/main/java/com/huemap/backend/common/response/error/ErrorResponse.java
- backend/src/main/java/com/huemap/backend/common/response/success/RestResponse.java
* RestResponse (성공 Response 클래스)
* data: 요청 정보
* ErrorResponse (실패 Response 클래스)
* status: http status code
* message: 에러에 대한 message
* errors: 요청 값에 대한 field, value, reason을 담음, 만약 errors에 바인딩 된 결과가 없다면 빈 배열[] 을 응답
> [#44] 성공 실패 공통 Response 클래스 생성

- backend/src/main/java/com/huemap/backend/common/presentation/ControllerAdvice.java
* Global Exception Handler 클래스 생성
* @Valid를 통해 RequestBody를 검증할 때 터지는 예외 handler를 미리 생성해두었습니다.
> [#43] exception handler 클래스 생성

- backend/src/main/java/com/huemap/backend/bin/domain/Bin.java
- backend/src/main/java/com/huemap/backend/bin/domain/BinType.java
> [#39] Bin Entity 생성

- backend/src/main/java/com/huemap/backend/bin/application/BinService.java
- backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinDetailMapper.java
- backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinMapper.java
- backend/src/main/java/com/huemap/backend/bin/dto/response/BinDetailResponse.java
- backend/src/main/java/com/huemap/backend/bin/dto/response/BinResponse.java
domain 아래에 mapper 디렉토리를 생성하였습니다
> [BE] BinDetailResponse 생성

- backend/build.gradle
- backend/src/main/resources/application.yml
hibernate 버전이 5.6.11.Final 라서 이와 동일한 hibernate-spatial 의존성을 추가하였습니다.
> [#53]  hibernate-spatial 의존성 추가

- backend/src/main/java/com/huemap/backend/common/validator/LatitudeValid.java
- backend/src/main/java/com/huemap/backend/common/validator/LatitudeValidator.java
- backend/src/main/java/com/huemap/backend/common/validator/LongitudeValid.java
- backend/src/main/java/com/huemap/backend/common/validator/LongitudeValidator.java
- backend/src/main/java/com/huemap/backend/report/application/ReportService.java
- backend/src/main/java/com/huemap/backend/report/domain/mapper/ClosureMapper.java
- backend/src/main/java/com/huemap/backend/report/dto/request/ClosureCreateRequest.java
- backend/src/main/java/com/huemap/backend/report/dto/response/ClosureCreateResponse.java
- backend/src/main/java/com/huemap/backend/report/presentation/ReportController.java
- backend/src/test/java/com/huemap/backend/report/presentation/ReportControllerTest.java
* 위도와 경도의 유효성 검사를 위한 애노테이션을 구현하였습니다.
* 위도와 경도 각각 정규식을 사용하여 범위 유효성 검사와 형식 유효성 검사를 하도록 하였습니다.
* Controller 구현
*  로그인된 사용자가 제보를 할 수 있는데, 현재 사용자 영역이 구현이 안되었으므로 `TODO` 주석 처리하였습니다.
* 사용자 입력값에 대한 controller 단위 테스트를 구현하였습니다.
> [#67] 폐쇄 폐수거함 제보 Controller 구현 (잘못된 폐수거함 제보)

- backend/src/main/java/com/huemap/backend/bin/application/BinService.java
- backend/src/main/java/com/huemap/backend/bin/domain/mapper/BinDetailMapper.java
- backend/src/main/java/com/huemap/backend/bin/dto/response/BinDetailResponse.java
- backend/src/main/java/com/huemap/backend/report/domain/ReportRepository.java
ReportRepository에서 count 쿼리 메소드를 쓰려고 했으나 반환형이 Long이라 Clouser을 명시할 수 없어서 쿼리 생성이 불가능한거 같아서  JPQL로 구현했습니다
> [BE] 폐수거함 상세 조회시 잘못된 폐수거함 제보 횟수를 response에 추가

- backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
- backend/src/main/java/com/huemap/backend/suggestion/application/SuggestionService.java
- backend/src/main/java/com/huemap/backend/suggestion/domain/Suggestion.java
- backend/src/main/java/com/huemap/backend/suggestion/domain/SuggestionRepository.java
- backend/src/main/java/com/huemap/backend/suggestion/domain/mapper/SuggestionCreateMapper.java
- backend/src/main/java/com/huemap/backend/suggestion/dto/request/SuggestionCreateRequest.java
- backend/src/main/java/com/huemap/backend/suggestion/dto/response/SuggestionCreateResponse.java
- backend/src/main/java/com/huemap/backend/suggestion/exception/SuggestionLimitExceededException.java
- backend/src/main/java/com/huemap/backend/suggestion/presentation/SuggestionController.java
하루 건의 최대치는 3번으로 제한하였습니다
하루 기준은 그 날의 00:00:00~23:59:59 로 설정하였습니다
폐수거함 조회 처럼 RequestParam이나 PathVariable이 아닌 dto 내에서  BinType을 받을 경우 
존재하지 않는 BinType임에도 에러를 발생시키지 않는 **버그**가 있습니다
https://jsy1110.github.io/2022/enum-class-validation/ 
따라서 해당 방식처럼 enum 전용 유효성검사 어노테이션을 다음 작업으로 만들도록 하겠습니다
그 후 지금까지 구현한 기능들에 대한 테스트 코드를 작성할 예정입니다
> [BE] 폐수거함 설치 건의 service구현

- .github/workflows/backend-ci.yml
- backend/build.gradle
- backend/src/main/java/com/huemap/backend/infrastructure/s3/S3Uploader.java
- backend/src/main/java/com/huemap/backend/infrastructure/s3/config/AwsConfig.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/huemap/backend/common/scheduler/SchedulerServiceIntegrationTest.java
- backend/src/test/java/com/huemap/backend/domain/bin/event/BinEventHandlerIntegrationTest.java
- backend/src/test/java/com/huemap/backend/infrastructure/openApi/KakaoMapProviderIntegrationTest.java
- backend/src/test/java/com/huemap/backend/infrastructure/s3/S3MockConfig.java
- backend/src/test/java/com/huemap/backend/infrastructure/s3/S3UploaderTest.java
- backend/src/test/resources/application.yml
aws s3 mock 서버를 띄워서 테스트를 수행하는 방향으로 구성하였습니다.
* s3upload 테스트는 profile test로 설정해서 실행됩니다.
application을 실행할 때는 profile 설정을 `prod` 로 설정하시면 됩니다.
> [#132] AWS S3 환경 설정 & 테스트

- web/src/view/binStatePage.vue
- web/src/view/selectGuPage.vue
> [WEB] 폐수거함 상태 소켓 이벤트시 마커 띄우기 구현

- backend/src/main/java/com/huemap/backend/common/annotation/AuthRequired.java
- backend/src/main/java/com/huemap/backend/common/annotation/CurrentUserId.java
- backend/src/main/java/com/huemap/backend/common/config/WebConfig.java
- backend/src/main/java/com/huemap/backend/common/exception/AuthException.java
- backend/src/main/java/com/huemap/backend/common/resolver/AuthInterceptor.java
- backend/src/main/java/com/huemap/backend/common/resolver/CurrentUserIdResolver.java
- backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
- backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
- backend/src/main/java/com/huemap/backend/domain/suggestion/presentation/SuggestionController.java
- backend/src/main/java/com/huemap/backend/domain/user/application/LoginService.java
- backend/src/main/java/com/huemap/backend/domain/user/application/SessionLoginService.java
- backend/src/main/java/com/huemap/backend/domain/user/presentation/UserController.java
- backend/src/test/java/com/huemap/backend/domain/bin/presentation/BinControllerTest.java
- backend/src/test/java/com/huemap/backend/support/ControllerTest.java
* 인터셉터를 통한 세션 로그인 기반 사용자 인증 구현
* controller 메소드단에 `@AuthRequired` 애노테이션을 붙이면 인터셉터에서 사용자 인증을 수행
* 메소드 파라미터에 `@CurrentId` 애노테이션을 선언한 변수를 선언하면 현재 로그인된 사용자 정보를 획득할 수 있습니다.
> [#168] 사용자 인증 구현

- backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
- backend/src/main/java/com/huemap/backend/domain/report/dto/response/ConditionResponse.java
- backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
폐수거함 상태 조회가 결국 폐수거함 상태 제보를 조회하는 것이기 때문에
기존에 api 설계에서 Bin 도메인에 있었던 폐수거함 상태 조회를 Report로 옮겼습니다
> [BE] 폐수거함 상태 조회 Controller 구현

- backend/src/test/java/com/huemap/backend/domain/user/presentation/UserControllerTest.java
> [#185] 회원가입, 로그인 비즈니스 에러 Controller 테스트

- backend/src/main/java/com/huemap/backend/common/config/WebConfig.java
- backend/src/main/java/com/huemap/backend/common/interceptor/AuthInterceptor.java
- backend/src/main/java/com/huemap/backend/common/response/error/ErrorCode.java
- backend/src/main/java/com/huemap/backend/domain/bin/application/BinService.java
- backend/src/main/java/com/huemap/backend/domain/bin/domain/BinRepository.java
- backend/src/main/java/com/huemap/backend/domain/report/application/ReportService.java
- backend/src/test/java/com/huemap/backend/domain/bin/application/BinServiceTest.java
- backend/src/test/java/com/huemap/backend/domain/report/application/ReportServiceTest.java
- backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
- backend/src/test/java/com/huemap/backend/support/ControllerTest.java
* 제보 도메인 비즈니스 에러 Controller 테스트 추가
* 인터셉터 패키지 경로 변경
* 변수명, 메소드명 변경
> [#187] 제보 도메인 비즈니스 에러 Controller 테스트

- data/app.py
- data/service/kmeansCluster.py
- web/src/view/binSuggestionPage.vue
- web/src/view/mainPage.vue
임의의 폐수거함 건의 데이터가 필요해 영등포구 일반 쓰렉레기통 데이터를 사용했습니다
이렇게 폐수거함 건의가 들어왔을 경우 4개의 그룹으로 나눈다면 눈대중으로 봤을때 빨간 선대로 그룹을 나눌 수 있을 것입니다
실제로 4개의 폐수거함을 설치하기 위해 클러스터링을 한다면 아래와 같은 결과를 얻을 수 있습니다
눈대중으로 봤을 때의 그룹과 일치하며 centroid간의 간격도 적당한 것을 볼 수 있습니다
> [WEB] 클러스터링 결과 마커 띄우기 구현

- backend/src/main/java/com/huemap/backend/common/presentation/ControllerAdvice.java
- backend/src/main/java/com/huemap/backend/domain/bin/presentation/BinController.java
- backend/src/main/java/com/huemap/backend/domain/report/presentation/ReportController.java
- backend/src/main/java/com/huemap/backend/domain/suggestion/presentation/SuggestionController.java
- backend/src/main/java/com/huemap/backend/domain/user/presentation/UserController.java
- backend/src/test/java/com/huemap/backend/domain/report/presentation/ReportControllerTest.java
컨트롤러에서 @LatitudeValid는 사용이 안되어서 @Range를 사용했습니다
> [BE] 폐수거함 상태 제보 요청 형식 수정
